name: technews
on:
  workflow_dispatch:
  schedule: 
    - cron: '30 22 * * *'
jobs:
  setup-and-test:
    runs-on: macos-latest  # 使用 macOS 环境
    
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "NowScott"
          git config --global user.email "nowscott@qq.com"
          git clone https://github.com/nowscott/EverydayTechNews.git
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 指定 Python 版本
      - name: Install Chrome and ChromeDriver
        run: |
          brew install --cask google-chrome
          brew install chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
      - name: Set Env
        env:
          SENDING_ACCOUNT: ${{secrets.SENDING_ACCOUNT}}
          SENDING_PASSWORD: ${{secrets.SENDING_PASSWORD}}
          SERVER: ${{secrets.SERVER}}
          NOTION_API_KEY: ${{secrets.NOTION_API_KEY}}
          NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
      - name: Run news_sorter.py
        run: |
          python src/news_sorter.py
      - name: Run main.py
        run: |
          python src/main.py
      - name: Commit changes
        run: |
          git add -A
          DATE=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M:%S")
          git commit -m "Update news file at $DATE" || echo "No changes to commit"
          git push