name: technews
on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
jobs:
  setup-and-test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Git
        run: |
          git config user.name "NowScott"
          git config user.email "nowscott@qq.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Chrome and ChromeDriver
        run: |
          brew install --cask google-chrome
          brew install chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run news_sorter.py
        run: |
          python src/news_sorter.py

      - name: Set Environment Variables and Run main.py
        env:
          SENDING_ACCOUNT: ${{ secrets.SENDING_ACCOUNT }}
          SENDING_PASSWORD: ${{ secrets.SENDING_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python src/main.py

      - name: Commit changes
        run: |
          git add -A
          DATE=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M:%S")
          git commit -m "Update news file at $DATE" || echo "No changes to commit"
          git push
