name: 排序并发送邮件
on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
jobs:
  setup-and-test:
    runs-on: macos-latest
    
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
      
      - name: 设置 Git
        run: |
          git config user.name "NowScott"
          git config user.email "nowscott@qq.com"

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装 Chrome 和 ChromeDriver
        run: |
          brew install --cask google-chrome
          brew install chromedriver

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: 运行 news_sorter.py
        run: |
          python src/news_sorter.py

      - name: 设置环境变量并运行 main.py
        env:
          SENDING_ACCOUNT: ${{ secrets.SENDING_ACCOUNT }}
          SENDING_PASSWORD: ${{ secrets.SENDING_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python src/main.py

      - name: 提交更改
        run: |
          git diff --quiet --exit-code news_archive/ || (
            git add news_archive/
            DATE=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M:%S")
            git commit -m "更新新闻文件于 $DATE"
            git push origin main
          )
